apiVersion: v1
kind: Service
metadata:
  name: {{ include "keyboard-signature.fullname" . }}
  labels:
    {{- include "keyboard-signature.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "keyboard-signature.selectorLabels" . | nindent 4 }}
