replicaCount: 1

image:
  repository: ghcr.io/kwright02/keyboard-signature
  tag: master
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources: {}

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: kwright02.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
